##############################################################
# update plugin
##############################################################
- block:
  - name: check .git in plugin dir
    stat:
      path: "{{ plugin_dir }}/{{ base_plugin_path }}/.git"
    register: is_plugin_from_git
  
  - debug:
      msg: "plugin name: {{ base_plugin_path }}"

  - name: update plugin from git
    become: yes
    become_user: "{{ redmine_owner }}"
    shell: "git {{ item }}"
    args:
      executable: "{{ shell }}"
      chdir: "{{ plugin_dir }}/{{ base_plugin_path }}"
    environment:
      http_proxy: "{{ http_proxy }}"
      PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    with_items:
      - "fetch"
      - "checkout {{ plugins[base_plugin_path] | default(default_branch) }}"
      - "pull"
    when: 
      - is_plugin_from_git.stat.exists == true
      - is_plugin_from_git.stat.isdir == true
      - plugins is defined
    ignore_errors: true
